---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tomcat-k8s

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tomcat-k8s
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: tomcat-k8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tomcat-k8s
subjects:
- kind: ServiceAccount
  name: tomcat-k8s
